// src/domain/manufacturing/ontology_extended_generated.c
// 自动生成的制造业类型定义代码
// 此文件由 tools/generate_manufacturing_types.py 自动生成
// 请勿手动编辑此文件
// 改造：使用 Prop 作为良构类型（KOS_ID/KOS_TIME 非良构），优先 kos-core 校验

#include "../../../include/kos_ontology.h"
#include "../../../include/kos_core.h"
#include "../../../include/kos_core_bridge.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

// 辅助函数：添加基础类型定义（优先 kos-core 校验，回退用 Prop 良构类型）
static void add_basic_type(TypeOntology* ontology, const char* name, term_kind kind) {
    char kos_expr[128];
    snprintf(kos_expr, sizeof(kos_expr), "Prop %s", name);
    char err[256];
    if (kos_core_bridge_available()) {
        if (kos_ontology_add_type_from_kos(ontology, name, kos_expr, NULL, err, sizeof(err)) == 0) {
            return;
        }
    }
    kos_term* type = kos_mk_prop(name);
    if (type && kos_type_wellformed(type)) {
        kos_ontology_add_type_definition(ontology, name, type, NULL);
        kos_term_free(type);
    }
}

// 添加所有生成的类型定义
int kos_manufacturing_ontology_add_generated_types(TypeOntology* ontology) {
    if (!ontology) {
        return -1;
    }
    
    printf("[Manufacturing] Adding generated types...\n");
    int count = 0;
    
    // ========== 标识符类型 ==========
    printf("[Manufacturing] Adding identifier types...\n");
    add_basic_type(ontology, "BatchID", KOS_ID);
    count++;
    add_basic_type(ontology, "ProductID", KOS_ID);
    count++;
    add_basic_type(ontology, "OrderID", KOS_ID);
    count++;
    add_basic_type(ontology, "WorkOrderID", KOS_ID);
    count++;
    add_basic_type(ontology, "SerialNumber", KOS_ID);
    count++;
    add_basic_type(ontology, "LotNumber", KOS_ID);
    count++;
    add_basic_type(ontology, "MaterialLotID", KOS_ID);
    count++;
    add_basic_type(ontology, "EquipmentID", KOS_ID);
    count++;
    add_basic_type(ontology, "MachineID", KOS_ID);
    count++;
    add_basic_type(ontology, "ToolID", KOS_ID);
    count++;
    add_basic_type(ontology, "StationID", KOS_ID);
    count++;
    add_basic_type(ontology, "LineID", KOS_ID);
    count++;
    add_basic_type(ontology, "WorkshopID", KOS_ID);
    count++;
    add_basic_type(ontology, "FactoryID", KOS_ID);
    count++;
    add_basic_type(ontology, "OperatorID", KOS_ID);
    count++;
    add_basic_type(ontology, "SupplierID", KOS_ID);
    count++;
    add_basic_type(ontology, "CustomerID", KOS_ID);
    count++;
    add_basic_type(ontology, "PartNumber", KOS_ID);
    count++;
    add_basic_type(ontology, "SKU", KOS_ID);
    count++;
    add_basic_type(ontology, "Barcode", KOS_ID);
    count++;
    add_basic_type(ontology, "QRCode", KOS_ID);
    count++;
    add_basic_type(ontology, "RFIDTag", KOS_ID);
    count++;
    add_basic_type(ontology, "PalletID", KOS_ID);
    count++;
    add_basic_type(ontology, "ContainerID", KOS_ID);
    count++;
    add_basic_type(ontology, "BoxID", KOS_ID);
    count++;
    add_basic_type(ontology, "PackageID", KOS_ID);
    count++;
    add_basic_type(ontology, "UnitID", KOS_ID);
    count++;
    add_basic_type(ontology, "AssemblyID", KOS_ID);
    count++;
    add_basic_type(ontology, "SubAssemblyID", KOS_ID);
    count++;
    add_basic_type(ontology, "ComponentID", KOS_ID);
    count++;
    add_basic_type(ontology, "RawMaterialID", KOS_ID);
    count++;
    add_basic_type(ontology, "FinishedGoodID", KOS_ID);
    count++;
    add_basic_type(ontology, "WIPID", KOS_ID);
    count++;
    add_basic_type(ontology, "ProcessID", KOS_ID);
    count++;
    add_basic_type(ontology, "OperationID", KOS_ID);
    count++;
    add_basic_type(ontology, "StepID", KOS_ID);
    count++;
    add_basic_type(ontology, "TaskID", KOS_ID);
    count++;
    add_basic_type(ontology, "ResourceID", KOS_ID);
    count++;
    add_basic_type(ontology, "WorkCenterID", KOS_ID);
    count++;
    add_basic_type(ontology, "CellID", KOS_ID);
    count++;
    add_basic_type(ontology, "ZoneID", KOS_ID);
    count++;
    add_basic_type(ontology, "LocationID", KOS_ID);
    count++;
    add_basic_type(ontology, "BinID", KOS_ID);
    count++;
    add_basic_type(ontology, "ShelfID", KOS_ID);
    count++;
    add_basic_type(ontology, "RackID", KOS_ID);
    count++;
    add_basic_type(ontology, "WarehouseID", KOS_ID);
    count++;
    add_basic_type(ontology, "StorageID", KOS_ID);
    count++;
    add_basic_type(ontology, "TransportID", KOS_ID);
    count++;
    add_basic_type(ontology, "VehicleID", KOS_ID);
    count++;
    add_basic_type(ontology, "RouteID", KOS_ID);
    count++;
    add_basic_type(ontology, "PathID", KOS_ID);
    count++;

    // ========== 时间类型 ==========
    printf("[Manufacturing] Adding temporal types...\n");
    add_basic_type(ontology, "Time", KOS_TIME);
    count++;
    add_basic_type(ontology, "Timestamp", KOS_TIME);
    count++;
    add_basic_type(ontology, "Duration", KOS_TIME);
    count++;
    add_basic_type(ontology, "Date", KOS_TIME);
    count++;
    add_basic_type(ontology, "TimeRange", KOS_TIME);
    count++;
    add_basic_type(ontology, "StartTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "EndTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "CycleTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "LeadTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "ProcessingTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "SetupTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "Downtime", KOS_TIME);
    count++;
    add_basic_type(ontology, "Uptime", KOS_TIME);
    count++;
    add_basic_type(ontology, "MaintenanceTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "IdleTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "WaitTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "QueueTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "ThroughputTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "TaktTime", KOS_TIME);
    count++;
    add_basic_type(ontology, "Interval", KOS_TIME);
    count++;

    // ========== 物理量类型 ==========
    printf("[Manufacturing] Adding physical quantity types...\n");
    add_basic_type(ontology, "Temperature", KOS_PROP);
    count++;
    add_basic_type(ontology, "TargetTemperature", KOS_PROP);
    count++;
    add_basic_type(ontology, "ActualTemperature", KOS_PROP);
    count++;
    add_basic_type(ontology, "MaxTemperature", KOS_PROP);
    count++;
    add_basic_type(ontology, "MinTemperature", KOS_PROP);
    count++;
    add_basic_type(ontology, "TemperatureRate", KOS_PROP);
    count++;
    add_basic_type(ontology, "TemperatureGradient", KOS_PROP);
    count++;
    add_basic_type(ontology, "Pressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "TargetPressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "ActualPressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "MaxPressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "MinPressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "PressureDifference", KOS_PROP);
    count++;
    add_basic_type(ontology, "VacuumPressure", KOS_PROP);
    count++;
    add_basic_type(ontology, "Voltage", KOS_PROP);
    count++;
    add_basic_type(ontology, "Current", KOS_PROP);
    count++;
    add_basic_type(ontology, "Power", KOS_PROP);
    count++;
    add_basic_type(ontology, "Energy", KOS_PROP);
    count++;
    add_basic_type(ontology, "Frequency", KOS_PROP);
    count++;
    add_basic_type(ontology, "Resistance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Capacitance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Inductance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Impedance", KOS_PROP);
    count++;
    add_basic_type(ontology, "PhaseAngle", KOS_PROP);
    count++;
    add_basic_type(ontology, "PowerFactor", KOS_PROP);
    count++;
    add_basic_type(ontology, "Speed", KOS_PROP);
    count++;
    add_basic_type(ontology, "Velocity", KOS_PROP);
    count++;
    add_basic_type(ontology, "Acceleration", KOS_PROP);
    count++;
    add_basic_type(ontology, "Force", KOS_PROP);
    count++;
    add_basic_type(ontology, "Torque", KOS_PROP);
    count++;
    add_basic_type(ontology, "Moment", KOS_PROP);
    count++;
    add_basic_type(ontology, "Stress", KOS_PROP);
    count++;
    add_basic_type(ontology, "Strain", KOS_PROP);
    count++;
    add_basic_type(ontology, "Displacement", KOS_PROP);
    count++;
    add_basic_type(ontology, "Vibration", KOS_PROP);
    count++;
    add_basic_type(ontology, "Noise", KOS_PROP);
    count++;
    add_basic_type(ontology, "Wear", KOS_PROP);
    count++;
    add_basic_type(ontology, "Length", KOS_PROP);
    count++;
    add_basic_type(ontology, "Width", KOS_PROP);
    count++;
    add_basic_type(ontology, "Height", KOS_PROP);
    count++;
    add_basic_type(ontology, "Depth", KOS_PROP);
    count++;
    add_basic_type(ontology, "Diameter", KOS_PROP);
    count++;
    add_basic_type(ontology, "Radius", KOS_PROP);
    count++;
    add_basic_type(ontology, "Thickness", KOS_PROP);
    count++;
    add_basic_type(ontology, "Area", KOS_PROP);
    count++;
    add_basic_type(ontology, "Volume", KOS_PROP);
    count++;
    add_basic_type(ontology, "Weight", KOS_PROP);
    count++;
    add_basic_type(ontology, "Mass", KOS_PROP);
    count++;
    add_basic_type(ontology, "Density", KOS_PROP);
    count++;
    add_basic_type(ontology, "Angle", KOS_PROP);
    count++;
    add_basic_type(ontology, "Rotation", KOS_PROP);
    count++;
    add_basic_type(ontology, "Orientation", KOS_PROP);
    count++;
    add_basic_type(ontology, "PositionX", KOS_PROP);
    count++;
    add_basic_type(ontology, "PositionY", KOS_PROP);
    count++;
    add_basic_type(ontology, "PositionZ", KOS_PROP);
    count++;
    add_basic_type(ontology, "FlowRate", KOS_PROP);
    count++;
    add_basic_type(ontology, "FlowVolume", KOS_PROP);
    count++;
    add_basic_type(ontology, "FlowVelocity", KOS_PROP);
    count++;
    add_basic_type(ontology, "PH", KOS_PROP);
    count++;
    add_basic_type(ontology, "Concentration", KOS_PROP);
    count++;
    add_basic_type(ontology, "Viscosity", KOS_PROP);
    count++;
    add_basic_type(ontology, "Moisture", KOS_PROP);
    count++;
    add_basic_type(ontology, "Humidity", KOS_PROP);
    count++;
    add_basic_type(ontology, "DewPoint", KOS_PROP);
    count++;
    add_basic_type(ontology, "Brightness", KOS_PROP);
    count++;
    add_basic_type(ontology, "Luminance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Color", KOS_PROP);
    count++;
    add_basic_type(ontology, "Reflectance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Transmittance", KOS_PROP);
    count++;
    add_basic_type(ontology, "Opacity", KOS_PROP);
    count++;
    add_basic_type(ontology, "Count", KOS_PROP);
    count++;
    add_basic_type(ontology, "Ratio", KOS_PROP);
    count++;
    add_basic_type(ontology, "Percentage", KOS_PROP);
    count++;
    add_basic_type(ontology, "Rate", KOS_PROP);
    count++;
    add_basic_type(ontology, "Efficiency", KOS_PROP);
    count++;
    add_basic_type(ontology, "Yield", KOS_PROP);
    count++;

    // ========== 状态和代码类型 ==========
    printf("[Manufacturing] Adding status code types...\n");
    add_basic_type(ontology, "ErrorCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "StatusCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "QualityGrade", KOS_PROP);
    count++;
    add_basic_type(ontology, "ProcessStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "EquipmentStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ProductStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "OrderStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "WorkOrderStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "BatchStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "MaterialStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "InventoryStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ShippingStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ReceivingStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "InspectionStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "MaintenanceStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "CalibrationStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "SafetyStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "EnvironmentalStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ComplianceStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "CertificationStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ApprovalStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "RejectionStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "PassStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "FailStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "WarningStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "AlertStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "CriticalStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "NormalStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "AbnormalStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "IdleStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "RunningStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "StoppedStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "MaintenanceMode", KOS_PROP);
    count++;
    add_basic_type(ontology, "SetupMode", KOS_PROP);
    count++;
    add_basic_type(ontology, "ProductionMode", KOS_PROP);
    count++;
    add_basic_type(ontology, "TestMode", KOS_PROP);
    count++;
    add_basic_type(ontology, "DebugMode", KOS_PROP);
    count++;
    add_basic_type(ontology, "ActiveStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "InactiveStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "EnabledStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "DisabledStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "LockedStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "UnlockedStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "OpenStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ClosedStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "OnStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "OffStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ReadyStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "BusyStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "ErrorStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "FaultStatus", KOS_PROP);
    count++;
    add_basic_type(ontology, "WarningCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "InfoCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "TraceCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "DebugCode", KOS_PROP);
    count++;
    add_basic_type(ontology, "SeverityLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "PriorityLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "UrgencyLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "RiskLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "CriticalityLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "ImpactLevel", KOS_PROP);
    count++;
    add_basic_type(ontology, "LikelihoodLevel", KOS_PROP);
    count++;

    printf("[Manufacturing] Generated %d basic types added successfully.\n", count);
    return 0;
}
